/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackRouteImport } from './routes/pack'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanIdRouteImport } from './routes/plan.$id'
import { Route as AuthFacebookCallbackRouteImport } from './routes/auth.facebook.callback'
import { Route as AuthInstagramCallbackRouteImport } from './routes/auth.instagram.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFacebookCallbackRoute = AuthFacebookCallbackRouteImport.update({
  id: '/auth/facebook/callback',
  path: '/auth/facebook/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInstagramCallbackRoute = AuthInstagramCallbackRouteImport.update({
  id: '/auth/instagram/callback',
  path: '/auth/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pack': typeof PackRoute
  '/privacy': typeof PrivacyRoute
  '/plan/$id': typeof PlanIdRoute
  '/auth/facebook/callback': typeof AuthFacebookCallbackRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pack': typeof PackRoute
  '/privacy': typeof PrivacyRoute
  '/plan/$id': typeof PlanIdRoute
  '/auth/facebook/callback': typeof AuthFacebookCallbackRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pack': typeof PackRoute
  '/privacy': typeof PrivacyRoute
  '/plan/$id': typeof PlanIdRoute
  '/auth/facebook/callback': typeof AuthFacebookCallbackRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pack'
    | '/privacy'
    | '/plan/$id'
    | '/auth/facebook/callback'
    | '/auth/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pack'
    | '/privacy'
    | '/plan/$id'
    | '/auth/facebook/callback'
    | '/auth/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/pack'
    | '/privacy'
    | '/plan/$id'
    | '/auth/facebook/callback'
    | '/auth/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackRoute: typeof PackRoute
  PrivacyRoute: typeof PrivacyRoute
  PlanIdRoute: typeof PlanIdRoute
  AuthFacebookCallbackRoute: typeof AuthFacebookCallbackRoute
  AuthInstagramCallbackRoute: typeof AuthInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/facebook/callback': {
      id: '/auth/facebook/callback'
      path: '/auth/facebook/callback'
      fullPath: '/auth/facebook/callback'
      preLoaderRoute: typeof AuthFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/instagram/callback': {
      id: '/auth/instagram/callback'
      path: '/auth/instagram/callback'
      fullPath: '/auth/instagram/callback'
      preLoaderRoute: typeof AuthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackRoute: PackRoute,
  PrivacyRoute: PrivacyRoute,
  PlanIdRoute: PlanIdRoute,
  AuthFacebookCallbackRoute: AuthFacebookCallbackRoute,
  AuthInstagramCallbackRoute: AuthInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
